### PR TITLE
Add logo

### LINKED ISSUE #29: Add a logo!
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #29 

This has by no means decided yet, just wanted to get some more progress regarding the logo and open a PR.

Would still like to keep all our awesome assets in the repo though!

You can find a preview of the logo-included Readme [here](https://github.com/xing/crep/blob/add_logo/Readme.md).

### CODE REVIEW

**Comment by q231950** [comment]
@BasThomas I think we decided for the 'natural crab', can you confirm?

**Comment by BasThomas** [comment]
That’s the one I put in the readme right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by q231950** [comment]
Yeah, correct. So this could be a real pr?

**Comment by q231950** [comment]
Or we wait a bit for more participation in #29 probably makes sense

**Comment by BasThomas** [comment]
🚢

**Pull request merged**
